# Generated by Django 3.2.4 on 2021-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_remove_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
