# Generated by Django 3.2.4 on 2021-06-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.TextField(default='', max_length=50),
        ),
    ]
