# Generated by Django 3.2.4 on 2021-06-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_alter_phone_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='slug',
        ),
    ]
